use_frameworks!

target 'QFLibraryKit_Example' do
  pod 'QFLibraryKit', :path => '../'

  target 'QFLibraryKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
